name: Build Holo Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.channel_tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - steamos_channel: steamdeck
            channel_tag: stable
            latest_tag: latest
            version_prefix: ''
          - steamos_channel: steamdeck-beta
            channel_tag: beta
            latest_tag: ''
            version_prefix: beta-
          - steamos_channel: steamdeck-preview
            channel_tag: preview
            latest_tag: ''
            version_prefix: preview-
          - steamos_channel: steamdeck-main
            channel_tag: main
            latest_tag: ''
            version_prefix: main-

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to GitHub Container Registry
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u SteamDeckHomebrew --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download SteamOS
      id: download
      run: ./download.sh "${{ matrix.steamos_channel }}" >>$GITHUB_OUTPUT

    - name: Build and tag base image
      run: |
        sudo ./build.sh

    - name: Cleanup SteamOS image
      run: rm -rf ./steamos_image ./steamos

    - name: Build Rust toolchain image
      run: |
        cd languages
        docker build -t holo-toolchain-rust:ci-build -f ./rust.dockerfile .

    - name: Build Go toolchain image
      run: |
        cd languages
        docker build -t holo-toolchain-go:ci-build -f ./go.dockerfile .

    - name: Tag images
      run: |
        channel_tag="${{ matrix.channel_tag }}"
        version_prefix="${{ matrix.version_prefix }}"
        version_tags="${version_prefix}${{ steps.download.outputs.BUILD_ID }} ${version_prefix}${{ steps.download.outputs.FULL_VERSION }} ${version_prefix}${{ steps.download.outputs.MAJOR_VERSION }} ${version_prefix}${{ steps.download.outputs.MINOR_VERSION }}"

        docker tag holo-base:ci-build ghcr.io/steamdeckhomebrew/holo-base:$channel_tag
        docker tag holo-toolchain-rust:ci-build ghcr.io/steamdeckhomebrew/holo-toolchain-rust:$channel_tag
        docker tag holo-toolchain-go:ci-build ghcr.io/steamdeckhomebrew/holo-toolchain-go:$channel_tag

        for version_tag in $version_tags
        do
          docker tag holo-base:ci-build ghcr.io/steamdeckhomebrew/holo-base:$version_tag
          docker tag holo-toolchain-rust:ci-build ghcr.io/steamdeckhomebrew/holo-toolchain-rust:$version_tag
          docker tag holo-toolchain-go:ci-build ghcr.io/steamdeckhomebrew/holo-toolchain-go:$version_tag
        done

        if [ -n "${{ matrix.latest_tag }}" ]; then
          docker tag holo-base:ci-build ghcr.io/steamdeckhomebrew/holo-base:${{ matrix.latest_tag }}
          docker tag holo-toolchain-rust:ci-build ghcr.io/steamdeckhomebrew/holo-toolchain-rust:${{ matrix.latest_tag }}
          docker tag holo-toolchain-go:ci-build ghcr.io/steamdeckhomebrew/holo-toolchain-go:${{ matrix.latest_tag }}
        fi

    - name: Wait for other runs to complete
      uses: softprops/turnstyle@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Base image
      run: docker push --all-tags ghcr.io/steamdeckhomebrew/holo-base

    - name: Push Rust toolchain image
      run: docker push --all-tags ghcr.io/steamdeckhomebrew/holo-toolchain-rust

    - name: Push Go toolchain image
      run: docker push --all-tags ghcr.io/steamdeckhomebrew/holo-toolchain-go

    - name: Log out of GitHub Container Registry
      run: |
        docker logout ghcr.io
